# Generated by Django 4.2.3 on 2023-09-09 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users1',
        ),
    ]
